export const S = {
  appTitle: "מתמטיקה לילדים",
  chooseKid: "מי משחק?",
  chooseTopicTitle: "בחר נושא",
  categoryMath: "חשבון",
  categoryLanguage: "שפה",
  categoryTrivia: "ידע כללי",
  comingSoon: "בקרוב…",
  topicArithmetic: "חשבון",
  topicArithmeticDesc: "חיבור, חיסור, כפל, חילוק ועוד",
  topicSequences: "סדרות מספרים",
  topicSequencesDesc: "מצא את המספר החסר בסדרה",
  topicWordProblems: "בעיות מילוליות",
  topicWordProblemsDesc: "שאלות בסיפור — קרא וחשב",
  topicFractions: "שברים",
  topicFractionsDesc: "הכר, השווה, חבר, כפול ועוד",
  topicHebrewLetters: "אותיות",
  topicHebrewLettersDesc: "הכר אותיות עברית",
  topicEnglishLetters: "אותיות אנגלית",
  topicEnglishLettersDesc: "הכר אותיות A–Z",
  topicClock: "שעון",
  topicClockDesc: "לקרוא את השעה",
  topicPowers: "חזקות",
  topicPowersDesc: "3² , 2³ , 10⁴ ועוד",
  topicTrivia: "ידע כללי",
  topicTriviaDesc: "אנשים מפורסמים מההיסטוריה",
  topicCountries: "מדינות ובירות",
  topicCountriesDesc: "בירות מדינות העולם",
  clockReadHour: "איזו שעה השעון מראה?",
  clockReadMinute: "כמה דקות?",
  clockReadFull: "מה השעה?",
  clockPick: "באיזה שעון רואים את השעה הזו?",
  clockAdd: (delta: string) => `מה השעה בעוד ${delta}?`,
  clockElapsed: "כמה זמן עבר?",
  clockHours: (h: number) => h === 1 ? "שעה" : h === 2 ? "שעתיים" : `${h} שעות`,
  clockMinutes: (m: number) => `${m} דקות`,
  startSession: "התחל!",
  back: "חזור",
  level: "רמה",
  problemOf: (n: number, total: number) => `שאלה ${n} מתוך ${total}`,
  answer: "תשובה",
  submit: "שלח",
  needHelp: "צריך עזרה?",
  correct: "נכון! 🎉",
  wrong: (ans: string) => `לא נכון. התשובה הנכונה: ${ans}`,
  next: "הבא",
  sessionComplete: "סיום!",
  summaryTitle: "סיכום",
  summaryCorrect: (n: number, total: number) => `ענית נכון על ${n} מתוך ${total} שאלות`,
  accuracyPct: (pct: number) => `דיוק: ${pct}%`,
  playAgain: "שחק שוב",
  goHome: "בית",
  levelUp: "⬆️ עלית רמה!",
  levelDown: "⬇️ ירדת רמה",
  levelSame: "",
  duration: "זמן",
  formatDuration: (seconds: number) => {
    const m = Math.floor(seconds / 60);
    const s = seconds % 60;
    return m > 0 ? `${m}:${String(s).padStart(2, "0")}` : `${s}″`;
  },

  adminTitle: "לוח בקרה",
  adminTabOverview: "סקירה",
  adminTabKid: "ילד ונושא",
  adminTabActivity: "פעילות אחרונה",
  adminColKid: "ילד",
  adminColTopic: "נושא",
  adminColLevel: "רמה",
  adminColSessions: "מפגשים",
  adminColAccuracy: "דיוק",
  adminColAnswered: "תשובות",
  adminColDate: "תאריך",
  adminColDuration: "זמן",
  adminPickKid: "בחר ילד",
  adminPickTopic: "בחר נושא",
  adminLevelOverTime: "רמת קושי לאורך זמן",
  adminNoData: "אין עדיין נתונים",
  adminCorrect: "נכון",
  adminWrong: "שגוי",
};
