export const S = {
  appTitle: "מתמטיקה לילדים",
  chooseKid: "מי משחק?",
  chooseTopicTitle: "בחר נושא",
  topicArithmetic: "חשבון",
  topicArithmeticDesc: "חיבור, חיסור, כפל, חילוק ועוד",
  topicSequences: "סדרות מספרים",
  topicSequencesDesc: "מצא את המספר החסר בסדרה",
  topicWordProblems: "בעיות מילוליות",
  topicWordProblemsDesc: "שאלות בסיפור — קרא וחשב",
  startSession: "התחל!",
  back: "חזור",
  level: "רמה",
  problemOf: (n: number, total: number) => `שאלה ${n} מתוך ${total}`,
  answer: "תשובה",
  submit: "שלח",
  needHelp: "צריך עזרה?",
  correct: "נכון! 🎉",
  wrong: (ans: string) => `לא נכון. התשובה הנכונה: ${ans}`,
  next: "הבא",
  sessionComplete: "סיום!",
  summaryTitle: "סיכום",
  summaryCorrect: (n: number, total: number) => `ענית נכון על ${n} מתוך ${total} שאלות`,
  accuracyPct: (pct: number) => `דיוק: ${pct}%`,
  playAgain: "שחק שוב",
  goHome: "בית",
  levelUp: "⬆️ עלית רמה!",
  levelDown: "⬇️ ירדת רמה",
  levelSame: "",
};
